### ISSUE TITLE
winpython link not working

### ISSUE THREAD

**Issue by monicagangwar** [darbula/pymote#16]
"https://code.google.com/p/winpython/"
the following link is not working
also, after creating the virtual environment manually on windows, when i do "pip install pymote"
i get the following error
![screenshot 45](https://cloud.githubusercontent.com/assets/8946358/10843833/4ef43514-7f21-11e5-931e-1edd0fb25117.png)

**Comment by darbula** [comment]
I have updated [documentation](https://pymote.readthedocs.org/en/latest/install/installation.html) with working link. I advise to use development version `pip install -e git+https://github.com/darbula/pymote.git#egg=Pymote`, for now.
