### ISSUE TITLE
NameError while installation in fedora 22

### ISSUE THREAD

**Issue by vivekanand1101** [darbula/pymote#17]
I have all the dependencies listed [here](https://pymote.readthedocs.org/en/latest/install/installation.html#requirements), then i tried  ``pip install pymote``. It gave NameError that it can't find name "sys_platform".

http://paste.fedoraproject.org/293662/30900114

In a hurry. If anybody could help, that would be great.

**Comment by darbula** [comment]
I have released 0.2.1 version since 0.2.0 used old version of distribute package not needed anymore that could cause problems. Please try now.

**Comment by vivekanand1101** [comment]
sorry, this still gave an error. Not the same and also i am not sure it has everything to do with pymote

http://paste.fedoraproject.org/293842/35708014/

**Comment by darbula** [comment]
Yes it seems that the problem is with installing scipy. Could you paste output of `pip freeze` here. Probably you have newer version of scipy than the one that is required 0.12 or less.

**Comment by vivekanand1101** [comment]
I had one install by ``dnf`` but i removed it, when i saw this error. ``pip freeze`` gave this:

http://paste.fedoraproject.org/293847/14483576

**Comment by darbula** [comment]
You should install scipy 0.12 or 0.11 and then try again with pymote.

**Comment by vivekanand1101** [comment]
I tried it and now i have scipy version 0.11.0 and numpy version 1.7.0. Installation of pymote version 0.2.1 went well but i still get an error when i compile the "Hello Distributed world" example. Error:

https://paste.fedoraproject.org/294254/84370281/
.

**Comment by darbula** [comment]
The problem is in line `import scipy.stats`. You can try manually importing in the python shell and see if you get the same error. If you do, the problem is still in scipy.

**Comment by vivekanand1101** [comment]
That one is clear now. But still no success in compilation of "hello dist. world". Error:

https://paste.fedoraproject.org/294276/44844034/

**Comment by darbula** [comment]
Do you have `PySide` installed?

**Comment by vivekanand1101** [comment]
I thought ``pymote`` would install it by itself. Sorry for this one.

**Comment by darbula** [comment]
Unfortunately no, this could and should probably change.

**Comment by vivekanand1101** [comment]
That step is done. The program gets compiled. But as given by the example [here](), ``net.show()`` should show the gui. But, even if ``matplotlib`` is imported, an error shows up:

https://paste.fedoraproject.org/294320/84505621/

I have tried changing the backend, i changed it to ``PySide``. It doesn't work. As soon as i do ``net.show()``. ``Segmentation fault`` occurs and i am out of ``"ipymote"``

**Comment by darbula** [comment]
Hello world tutorial is intended to be started in `ipython notebook` as noted on tutorial page [here](https://pymote.readthedocs.org/en/latest/tutorials/hello_distributed_world.html#hello-distributed-world):

> Tutorial is currently available in form of IPython notebook

So you have to download notebook, start `ipython notebook --profile=pymote` and load it there.

**Comment by vivekanand1101** [comment]
Yeah. But, i was able to solve the problem. It was due to matplotlib. Would that be better to have animation as one of the feature ? Ex: like showing data transfer between motes.

**Comment by darbula** [comment]
Possibility to see data packages step by step is already in the simulationgui.
